---
title: "README"
output: github_document
---

## Data
- `data_org/` - source data for formatting
- `data_fmt/` - formatted data
  - `vector_data.csv` - formatted fish data
    - `tag_id`: PIT tag id
    - `occasion`: sampling occasion at capture
    - `species`: species code
    - `stream`: stream name
    - `weight_1`: g wet weight at capture
    - `length_1`: mm total body length at capture
    - `section_1`: stream section number at capture
    - `julian_1`: julian date at capture
    - `weight_2`: g wet weight at recapture
    - `length_2`: mm total body length at recapture
    - `section_2`: stream section number at recapture
    - `julian_2`: julian date at recapture
    - `occasion_2`: sampling occasion at recapture
    - `diff_length`: length difference between capture and recapture
  - `flow_summary.csv` - formatted water level data
    - `occasion`: sampling occasion
    - `stream`: stream name
    - `q50`: median water level
    - `q99_event`: occurrence of extreme high flows exceeding 99th percentile of daily water levels
  - `temp_summary.csv` - formatted temperature data
    - `occasion`: sampling occasion
    - `stream`: stream name
    - `mu_temp`: mean temperature

## Script

### Data analysis (`bayes_model/`)

- `inits_model_laplace.R` - R script to run a Bayes model
- `model_laplace.R` - JAGS code for a Laplace dispersal model

### Figures & Tables

- `figure_est` - figure for estimated parameters of bayesian dispersal model
- `figure_kernel` - figure for estimated dispersal kernels
- `si_figure_hist_bhc` - histogram for dispersal distance of bluehead chub
- `si_figure_hist_crc` - histogram for dispersal distance of creek chub
- `si_figure_hist_stj` - histogram for dispersal distance of striped jumprock
- `si_table_est_q50` - table for estimated parameters of bayesian dispersal model (median flow)
- `si_table_est_q99` - table for estimated parameters of bayesian dispersal model (high flow)
- `si_table_mr_summary` - table for descriptive statistics of mark-recapture data
- `si_table_waic` - table for WAIC comparisons

### rmd files

- `figures` - rmarkdown file to compile figures
- `support-info` - rmarkdown file to compile supporting information

## Session information

```{r, echo = FALSE, message = FALSE}
library(tidyverse)
sessionInfo()
```

